### ISSUE TITLE
proje ver 0.6

### ISSUE THREAD

**Issue by uzeyir-yariz** [uzeyir-yariz/proje#3]
### fifth section buna benzemeli
![Image](https://user-images.githubusercontent.com/99393019/201280361-39e7f0b3-71a3-42bc-9a07-f8d13a89e7c2.png)

### todo list

- [x] article > h3, hr, p _**flex collum**_
- [x] bir yorum formatı hazırla
![image](https://user-images.githubusercontent.com/99393019/201467478-111dcd96-9e43-43ed-9158-bdc6f4a7ddce.png)
- [x] yorum css layout dök 
- [x] figure > css

### bug fix

- [x] ekran küçülünce dışarı sızıyor **sızan tarafı bul _DÜZELT_**  
- [x] **section second ve third** arka planı daha okunur hale getir

![Image](https://user-images.githubusercontent.com/99393019/201361813-59c6a8e6-ce06-413f-9693-58b0745aa180.png)

![Image](https://user-images.githubusercontent.com/99393019/201361701-7f6f3b90-e009-46d8-b4c1-9afbf01c9593.png)

**Comment by uzeyir-yariz** [comment]
tamamlandı
