### ISSUE TITLE
ver 0.7

### ISSUE THREAD

**Issue by uzeyir-yariz** [uzeyir-yariz/proje#4]
## proje ver 0.7
FOOTER buna benzemeli 
![image](https://user-images.githubusercontent.com/99393019/201479006-ccdc90ed-1b5a-4487-be01-fcdacfa957e6.png)

### TODO LİST

- [x] footer layout _canva_ çıkar 
![image](https://user-images.githubusercontent.com/99393019/201922954-e7b2200a-79da-4421-b9c6-f31db40a9a89.png)
- [x] footer layout ekle 
- [x] footer içine div ekle **yan yana duracak**
- [x] divlerin içine bilgi eklenecek

#5 

- [x] alt taraf yumuşak geçiş uygula
