### ISSUE TITLE
proje ver 0.8

### ISSUE THREAD

**Issue by uzeyir-yariz** [uzeyir-yariz/proje#6]
# proje ver 0.8

- [x] yeni bir sayfa oluştur [`hakkımızda`](https://github.com/uzeyir-yariz/proje/issues/8)
- [x] yeni bir sayfa oluştur [`galeri`](https://github.com/uzeyir-yariz/proje/issues/7)
- [x] yeni bir sayfa oluştur[ `iletişim`](https://github.com/uzeyir-yariz/proje/issues/9)
- [x] yeni bir sayfa oluştur [`haberler`](https://github.com/uzeyir-yariz/proje/issues/11)

## ana görev

- [x] tüm sayfalarda nav'ı değiştir 

### [bug fix](https://github.com/uzeyir-yariz/proje/issues/5)
